fr_dict = {"message":"Afin d'encourager la mobilité durable, votre employeur vous propose les options suivantes:"
      "budget":"Budget/prime mobilité durable",
      "wfh":"Possibilité de télétravailler au domicile",
      "wftp":"Possibilité de travailler dans un tiers-lieu",
      "tpg_pass":"Prise en charge abo UNIRESO (TPG)",
      "lex_pass":"Prise en charge abo Léman Pass", 
      "cff_pass_ag":"Prise en charge abo CFF (AG) tout ou en partie",
      "cff_pass_dtp":"Prise en charge abo CFF (1/2 tarif plus)",
      "cff_pass_dt":"Prise en charge abo CFF (1/2 tarif)",
      "pnr_pass":"Prise en charge partielle abo P+R",
      "shuttle":"Navette last-mile depuis la gare la plus proche",
      "velo_station":"Prise en charge abo vélostation",              
      "bike_subs":"Subvention à l'achat d'un vélo / vélo électrique",
      "shower":"Mise à disposition de vestiaire et douches",
      "bike_parking":"Places de stationnement sécurisé vélo",
      "ebike_charging":"Possibilité de chargement batterie vélo électrique",
      "bike_equipment":"Remboursement d'équipement de sécurité et confort vélo",
      "carpool_subs":"Prise en charge des trajets en covoiturage",
      "carpool_connect":"Mise en relation covoiturage avec collègues au sein de l'entreprise",
      "carpool_parking":"Places de stationnement réservées covoiturage",
      "ev_charging":"Bornes de chargement véhicule électrique",
      "mobility_pass":"Prise en charge abo mobility car-sharing",
      "ebike_fleet":"Flotte de vélos électriques d'entreprise à disposition pour déplacements pro",
      "tpu_pro":"Prise en charge abo UNIRESO (TPG)",
      "train_pro":"Prise en charge abo CFF (Abonnement Général)","Politique de substitution de l'avion par le train",
      "ev_fleet":"Véhicules électriques d'entreprise à disposition pour déplacements pro"
}
en_dict = {"message":"In order to encourgae sustainable mobility choices, your employer provides you with the following options:"
      "budget":"Sustainable mobility budget",
      "wfh":"Ability to work from home",
      "wftp":"Ability to work remotely",
      "tpg_pass":"Public transport (UNIRESO) pass",
      "lex_pass":"Léman express pass", 
      "cff_pass_ag":"Train pass (general pass)",
      "cff_pass_dtp":"Train pass (1/2 fare plus)",
      "cff_pass_dt":"Train pass (1/2 fare)",
      "pnr_pass":"Park and Ride pass",
      "shuttle":"Shuttle from the enarest train station",
      "velo_station":"Velo-station pass",              
      "bike_subs":"Subsidy for the purchase of a bicycle/e-bike",
      "shower":"Showers, lockers and changing rooms",
      "bike_parking":"Secure bicycle parking",
      "ebike_charging":"E-bike battery charging",
      "bike_equipment":"Subsidy for the purchase of bicycle safety and comfort gear",
      "carpool_subs":"Reimbursement of car-pooling journeys",
      "carpool_connect":"Connection to nearby colleagues to facilitate car-pooling",
      "carpool_parking":"Parking spots reserved for car-pooling",
      "ev_charging":"EV charging at the workplace",
      "mobility_pass":"Mobility car-sharing pass",
      "ebike_fleet":"E-bike fleet for professional trips",
      "tpu_pro":"Public transport (UNIRESO) pass",
      "train_pro":"Train pass (general pass)",
      "ev_fleet":"EV fleet for professional trips"
}
